classdef clLPTNDesignerDetailSettingPanal < handle
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here
    properties
        main_figure
        losses_figure
        sensor_figure
        change_res_figure
        add_losses_figure
        add_sensors_figure
        Component_temperature_figure
        Component_output_figure
        
        lptn_all_components_information_table
        lptn_all_components_information_table_data
        
        lptn_build_system_pb
        lptn_AddLosses_table
        lptn_AddLosses_show_table
        lptn_AddSensors_table
        lptn_AddSensors_show_table
        lptn_loss_choose_components_table
        lptn_sensors_choose_components_table
        
        lptn_components_chosen
        lptn_AddLosses_data_settings
        lptn_AddLosses_table_data_components = {};
        lptn_AddLosses_table_data_settings = {};
        
        lptn_ChooseComponents_edit = {};
        lptn_ChooseComponents_popup = {};
        lptn_sensor_measurement_popup = {};
        lptn_sensors_components_checkbox_chosen
        
        lptn_sensors_choose_components_axial_position
        lptn_sensors_choose_components_radial_position
        lptn_sensors_choose_components_tangential_position
        
        lptn_AddSensors_table_data_components = {};
        lptn_AddSensors_table_data_position = {};
        lptn_AddSensors_table_data_measurement = {};
        
        
        lptn_Component_temperature_table
        lptn_Component_output_table
        
        lptn_allglobalsettings
        
        lptn_Component_temperature_input = {};
        lptn_Component_temperature_dimension
        
        lptn_Component_temperature_choose
        lptn_initial_temperature
        
        lptn_sensors_thermalsetting1
        lptn_sensors_thermalsetting2
        lptn_sensors_thermalsetting3
        
        lptn_initial_temperature_edit
        flux_name
        refer_temperature
        temperature_dependency_beta
        temperature_dependency
        flux_gain
        refer_temperature_edit
        temperature_dependency_beta_edit
        temperature_dependency_edit
        flux_gain_edit
        
        component_size_radial
        component_size_radial_in
        component_size_radial_out
        component_size_tangential
        component_size_axial
        lptn_change_res_text
        lptn_res_setting_pb
        loss_edit_row
        loss_edit_col
        edit_col
        edit_row
        lptn_resolution_table
        sensor_position_x={};
        sensor_position_y={};
        sensor_position_z={};
        lptn_components
        lptn_dimension_radial
        lptn_dimension_tangential
        lptn_dimension_axial
        lptn_single_unit
    end
    
    properties
        data
    end
    
    methods
        function obj = clLPTNDesignerDetailSettingPanal(varargin)
            if ishandle(varargin{1})
                obj.main_figure = varargin{1};
                obj.data = varargin{2};
            end
            obj.open_detailgui()
        end
        
        
        function open_detailgui(obj)
            obj.lptn_change_res_text = uicontrol('parent',obj.main_figure,'style','text',...
                'units','normalized','Position',[0.03 0.92 0.2 0.05],...
                'string','Resolutions:','Fontsize',10);
            
            obj.lptn_res_setting_pb = uicontrol('parent',obj.main_figure,'style','pushbutton',...
                'units','normalized','Position',[0.25 0.92 0.24 0.05],...
                'Fontsize',9,'callback',@obj.lptn_res_setting_pb_callback,'string','Change resolutions');
            
            uicontrol('parent',obj.main_figure,'style','text',...
                'units','normalized','Position',[0.06 0.79 0.1 0.1],...
                'string','Losses:','Fontsize',10);
            uicontrol('parent',obj.main_figure,'style','pushbutton',...
                'units','normalized','Position',[0.25 0.848 0.15 0.042],...
                'Fontsize',9,'callback',@obj.lptn_add_loss_pb_callback,'string','Add losses');
            uicontrol('parent',obj.main_figure,'style','text',...
                'units','normalized','Position',[0.06 0.71 0.1 0.1],...
                'string','Sensors:','Fontsize',10);
            uicontrol('parent',obj.main_figure,'style','pushbutton',...
                'units','normalized','Position',[0.25 0.77 0.15 0.042],...
                'Fontsize',9,'callback',@obj.lptn_add_sensor_pb_callback,'string','Add sensors');
            
            uicontrol('parent',obj.main_figure,...
                'style','text',...
                'units','normalized','Position',[0.5 0.86 0.3 0.1],...
                'string','Global initial temperature:','Fontsize',10);
            
            obj.lptn_initial_temperature_edit = uicontrol('parent',obj.main_figure,...
                'style','edit',...
                'units','normalized','Position',[0.84 0.92 0.08 0.04],...
                'Fontsize',10,...
                'callback',@obj.lptn_initial_temperature_callback);
            
            uicontrol('parent',obj.main_figure,...
                'style','text',...
                'units','normalized','Position',[0.5 0.78 0.34 0.1],...
                'string','Component temperature input:','Fontsize',10);
            
            uicontrol('parent',obj.main_figure,...
                'style','text',...
                'units','normalized','Position',[0.47 0.704 0.29 0.1],...
                'string','Component output:','Fontsize',10);
            
            uicontrol('parent',obj.main_figure,'style','pushbutton',...
                'units','normalized','Position',[0.84 0.838 0.12 0.05],...
                'Fontsize',9,'callback',@obj.lptn_Component_temperature_callback,'string','Add');
            uicontrol('parent',obj.main_figure,'style','pushbutton',...
                'units','normalized','Position',[0.84 0.765 0.12 0.05],...
                'Fontsize',9,'callback',@obj.lptn_Component_output_callback,'string','Add');
            columnformat = {'char','logical','char','char','char','char','char','char','char','char','logical','logical'};
            obj.lptn_all_components_information_table = uitable('parent',obj.main_figure,...
                'units','normalized','Position',[0.01 0.14 0.97 0.61],...
                'ColumnFormat', columnformat,...
                'ColumnEditable',[false false false false false false false false false false],...
                 'CellSelectionCallback',@obj.SelectionCallback,...
                'ColumnName', {'Components','Single unit','Axial','Radial','Tangential','Losses','Sensors','Entry temperature','Dimensions','Initial temperature',...
                'Average temperature','Hotspot temperature',},'RowName','',...
                'ColumnWidth',{100,65,40,40,40,40,40,70,70,70,70,70},'Data','');
             uicontrol('parent',obj.main_figure,...
                        'units','normalized','Position',[0.58 0.08 0.15 0.05],...
                        'style','pushbutton',...
                        'Fontsize',9,...
                        'callback',@obj.lptn_delete_pb_callback,...
                        'string','Delete sensor');
                     uicontrol('parent',obj.main_figure,...
                        'units','normalized','Position',[0.58 0.02 0.15 0.05],...
                        'style','pushbutton',...
                        'Fontsize',9,...
                        'callback',@obj.lptn_edit_pb_callback,...
                        'string','Edit sensor');
        end
        
         function SelectionCallback(obj,~,callbackdata)
           if length(callbackdata.Indices)>1
               obj.edit_row= callbackdata.Indices(1);
           obj.edit_col= callbackdata.Indices(2);
           end
         end
        
        function lptn_delete_pb_callback(obj, ~,~)
         obj.lptn_all_components_information_table_data{obj.edit_row,obj.edit_col} = '';
         set(obj.lptn_all_components_information_table,'data',obj.lptn_all_components_information_table_data);
         x=find(strcmp(obj.data.lptn_sensors,obj.data.lptn_components{obj.edit_row}));
         obj.data.lptn_sensors{x,1}='';
         obj.data.lptn_sensors{x,2}='';
         obj.data.lptn_sensors{x,3}='';
        end
    
         function lptn_edit_pb_callback(obj, ~,~)
              x= strcmp(obj.data.lptn_sensors,obj.data.lptn_components{obj.edit_row});
              if obj.data.lptn_apply_state== 0
                warndlg('The machine has not been constructed yet.');
            else
                     if isempty(obj.add_sensors_figure)|| ~ishandle(obj.add_sensors_figure)
                    obj.add_sensors_figure = figure('menubar','none','name','Sensors settings','resize','on','position',[200 100 1000 800]);
                    movegui(obj.add_sensors_figure,'center');
                    
                    for index = 1:length(obj.data.lptn_components)
                        obj.lptn_sensors_components_checkbox_chosen{index}= false;
                    end
                    obj.lptn_sensors_components_checkbox_chosen{obj.edit_row}= true;
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.85 0.2 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','1.Choose components');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.005 0.43 0.15 0.05],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','2.Set position');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.25 0.2 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','3.Choose measurements:');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.02 0.18 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','4.Set xxx:');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.14 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Clamped');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.10 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Inserted');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.06 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Clamped');
                    
                    lptn_choose_components_data = [obj.data.lptn_components,obj.lptn_sensors_components_checkbox_chosen'];
                    obj.lptn_sensors_choose_components_table = uitable('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.5 0.5 0.4],...
                        'ColumnFormat', {'char','logical'},...
                        'ColumnEditable',[false,false],...
                        'CellEditCallback',@obj.SensorsCheckboxEditCallback,...,...
                        'ColumnName', {'Components','Check'},'RowName','',...
                        'ColumnWidth',{205},'Data',lptn_choose_components_data);
                    
                    NumSymProperties= {};
                    len_cellnum = length(obj.data.lptn_cell_numsym);
                    for index = 1: len_cellnum
                        NumSymProperties{index} = char(obj.data.lptn_cell_numsym{index}.symbolic);
                    end
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.42 0.1 0.03],...
                        'style','text',...
                        'Fontsize',9,...
                        'string','Axial');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.15 0.434 0.4 0.027],...
                        'style','pop',...
                        'Fontsize',9,...
                        'string',NumSymProperties,...
                        'callback',@obj.Axial_popup_callback);
                    obj.lptn_sensors_choose_components_axial_position = uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.15 0.43 0.24 0.031],...
                        'Fontsize',9,'string','');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.385 0.09 0.03],...
                        'style','text',...
                        'Fontsize',9,...
                        'string','Radial');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.15 0.39 0.255 0.031],...
                        'style','pop',...
                        'Fontsize',9.5,...
                        'string',NumSymProperties,...
                        'callback',@obj.Radial_popup_callback);
                    obj.lptn_sensors_choose_components_radial_position = uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.15 0.388 0.24 0.032],...
                        'Fontsize',9,'string','');
                    
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.03 0.35 0.13 0.03],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Tangential');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.15 0.349 0.255 0.031],...
                        'style','pop',...
                        'Fontsize',9.5,...
                        'string',NumSymProperties,...
                        'callback',@obj.Tangential_popup_callback);
                    obj.lptn_sensors_choose_components_tangential_position = uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.15 0.348 0.24 0.030],...
                        'Fontsize',9,'string','');
                    
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.45 0.34 0.1 0.05],...
                        'style','text',...
                        'Fontsize',10,...
                        'string','Relative');
                    
                    
                    uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.43 0.35 0.0446 0.05],...
                        'Fontsize',9,...
                        'callback',@obj.Callback_lptn_sensors_setting_position_relative);
                    
                    obj.lptn_sensors_thermalsetting1 = uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.09 0.21 0.065 0.04],...
                        'Fontsize',9,...
                        'callback',@obj.lptn_sensors_thermalsetting1_callback);
                    obj.lptn_sensors_thermalsetting2 = uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.09 0.17 0.065 0.04],...
                        'Fontsize',9,...
                        'callback',@obj.lptn_sensors_thermalsetting2_callback);
                    obj.lptn_sensors_thermalsetting3 = uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.09 0.13 0.065 0.04],...
                        'Fontsize',9,...
                        'callback',@obj.lptn_sensors_thermalsetting3_callback);
                    
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.12 0.21 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.3 0.21 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.12 0.17 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.3 0.17 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.12 0.13 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.3 0.13 0.15 0.031],...
                        'Fontsize',9,'string','');
                    
                    MeasurementXaxis= {''};
                    len_cellmeasure = length(obj.data.lptn_cell_measurement);
                    for index = 1: len_cellmeasure
                        MeasurementAdded = obj.data.lptn_cell_measurement{index};
                        MeasurementXaxis{end+1} = MeasurementAdded{1,2};
                    end
                    
                    obj.lptn_sensor_measurement_popup{end+1} = uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.26 0.445 0.06],...
                        'style','pop',...
                        'Fontsize',9,...
                        'string',MeasurementXaxis);
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.8 0.04 0.115 0.04],...
                        'style','pushbutton',...
                        'Fontsize',9,...
                        'string','Next',...
                        'callback',@obj.AddSensors_next_edit_callback);
                    
                    obj.data.ShowGlobalNumSym(obj.add_sensors_figure,[0.63 0.7 0.31 0.2])
                    obj.data.ShowGlobalMotorinput(obj.add_sensors_figure,[0.63 0.43 0.31 0.2])
                    obj.data.ShowMeasurement(obj.add_sensors_figure,[0.63 0.133 0.31 0.25])
                     lptn_choose_components_data = [obj.data.lptn_components,obj.lptn_sensors_components_checkbox_chosen'];
              set(obj.lptn_sensors_choose_components_table,'data',lptn_choose_components_data);
              set(obj.lptn_sensors_choose_components_axial_position,'String',obj.sensor_position_x{x});
              set(obj.lptn_sensors_choose_components_radial_position,'String',obj.sensor_position_y{x});
              set(obj.lptn_sensors_choose_components_tangential_position,'String',obj.sensor_position_z{x});
             
                elseif ishandle(obj.add_sensors_figure)
                    figure(obj.add_sensors_figure)
                end
            end
              
             
         end
        function lptn_res_setting_pb_callback(obj, ~,~)
            if obj.data.lptn_apply_state== 0
                warndlg('The machine has not been constructed yet.');
            else
                if isempty(obj.change_res_figure)|| ~ishandle(obj.change_res_figure)
                    row = length(obj.data.lptn_components);
                    columnformat = {'char','logical','numeric','numeric','numeric'};
                  
           
                    resolution_table_data=[obj.data.lptn_components,obj.data.lptn_single_unit',obj.data.lptn_dimension_radial',...
                        obj.data.lptn_dimension_tangential',obj.data.lptn_dimension_axial'];
                    obj.change_res_figure = figure('menubar','none','name','Resolution settings','resize','on',...
                        'position',[200 100 800 500]);
                    movegui(obj.change_res_figure,'center');
                    set(obj.change_res_figure,'CloseRequestFcn',@obj.change_res_figure_my_closereq);
                    obj.lptn_resolution_table = uitable('parent',obj.change_res_figure,...
                        'units','normalized','Position',[0.1 0.25 0.8 0.6],...
                        'ColumnFormat', columnformat,...
                        'ColumnEditable',[false true true true true],...
                        'ColumnName', {'Components','Is it a single unit?','Dimension radial','Dimension tangential ','Dimension axial'},'RowName','',...
                        'ColumnWidth',{183,95,120,120,120},'Data',resolution_table_data);
                    
                      
                   
                obj.lptn_single_unit=obj.data.lptn_single_unit;
                obj.lptn_dimension_radial=obj.data.lptn_dimension_radial;
                obj.lptn_dimension_tangential=obj.data.lptn_dimension_tangential;
                obj.lptn_dimension_axial=obj.data.lptn_dimension_axial;
                   
                    uicontrol('parent',obj.change_res_figure,'style','pushbutton',...
                        'units','normalized','Position',[0.9 0.1 0.06 0.046],...
                        'Fontsize',9,'callback',@obj.apply_resolution_pb_callback,'string','OK');
                    set(obj.lptn_resolution_table,'Tag','myTableTag')
                elseif ishandle(obj.change_res_figure)
                    figure(obj.change_res_figure)
                end
            end
        end
        
        function change_res_figure_my_closereq(obj, ~, ~)
          selection = questdlg('Do you want to save your settings?',...
                'Close Request Function',...
                'Save','Do not save','Save');
            switch selection
                case 'Save'
            obj.data.lptn_single_unit=obj.lptn_single_unit;
            obj.data.lptn_dimension_radial=obj.lptn_dimension_radial;
            obj.data.lptn_dimension_tangential=obj.lptn_dimension_tangential;
            obj.data.lptn_dimension_axial=obj.lptn_dimension_axial;
            obj.lptn_all_components_information_table_data(:,2) = obj.data.lptn_single_unit';
            obj.lptn_all_components_information_table_data(:,3) = obj.data.lptn_dimension_radial';
            obj.lptn_all_components_information_table_data(:,4) = obj.data.lptn_dimension_tangential';
            obj.lptn_all_components_information_table_data(:,5) = obj.data.lptn_dimension_axial';
            set(obj.lptn_all_components_information_table,'data',obj.lptn_all_components_information_table_data);
                    delete(gcf)
                case 'Do not save'
                    delete(gcf)
            end
            
        end 
        
        function ResolutionEditCallback(obj,~,callbackdata)
            myfigure=findobj('Tag','myTableTag');
            index_r = callbackdata.Indices(1);
            index_c = callbackdata.Indices(2);
            switch index_c
                case  2
                    if callbackdata.EditData== true
                        obj.lptn_single_unit{index_r} = true;
                        obj.lptn_dimension_radial{index_r} = 1;
                        obj.lptn_dimension_tangential{index_r} = 1;
                        obj.lptn_dimension_axial{index_r} = 1;
                    else obj.lptn_single_unit{index_r} = 0;
                    end
                case  3
                    if obj.lptn_single_unit{index_r} == true
                        obj.lptn_dimension_radial{index_r} = 1;
                    else
                        obj.lptn_dimension_radial{index_r} = str2double(callbackdata.EditData);
                    end
                case  4
                    if obj.lptn_single_unit{index_r} == true
                        obj.lptn_dimension_tangential{index_r} = 1;
                    else
                        obj.lptn_dimension_tangential{index_r} = str2double(callbackdata.EditData);
                    end
                case  5
                    if obj.lptn_single_unit{index_r} == true
                        obj.lptn_dimension_axial{index_r} = 1;
                    else
                        obj.lptn_dimension_axial{index_r} = str2double(callbackdata.EditData);
                    end
            end
            myTestData = [obj.data.lptn_components,obj.lptn_single_unit',obj.lptn_dimension_radial',...
                obj.lptn_dimension_tangential',obj.lptn_dimension_axial'];
            set(findobj(myfigure,'Tag','myTableTag'),'Data',myTestData)
        end
        
        function apply_resolution_pb_callback(obj, ~,~)
           
            obj.data.lptn_single_unit=obj.lptn_single_unit;
            obj.data.lptn_dimension_radial=obj.lptn_dimension_radial;
            obj.data.lptn_dimension_tangential=obj.lptn_dimension_tangential;
            obj.data.lptn_dimension_axial=obj.lptn_dimension_axial;
            obj.lptn_all_components_information_table_data(:,2) = obj.data.lptn_single_unit';
            obj.lptn_all_components_information_table_data(:,3) = obj.data.lptn_dimension_radial';
            obj.lptn_all_components_information_table_data(:,4) = obj.data.lptn_dimension_tangential';
            obj.lptn_all_components_information_table_data(:,5) = obj.data.lptn_dimension_axial';
            set(obj.lptn_all_components_information_table,'data',obj.lptn_all_components_information_table_data);
            delete(gcf)
        end
        
        function lptn_initial_temperature_callback(obj, eventdata,~)
            if isempty(str2num(eventdata.String))
                set(obj.lptn_initial_temperature_edit,'String','0');
                warndlg('Input must be numerical');
            else
                obj.lptn_initial_temperature = eventdata.String;
                for index = 1:length(obj.data.lptn_components)
                    obj.data.lptn_initial_temperature{index} = obj.lptn_initial_temperature;
                end
            end
        end
        
        function lptn_add_loss_pb_callback(obj, ~,~)
            if obj.data.lptn_apply_state== 0
                warndlg('The machine has not been constructed yet.');
            else
                if isempty(obj.losses_figure)|| ~ishandle(obj.losses_figure)
                    obj.losses_figure = figure('menubar','none','name','Losses settings','resize','on','position',[200 100 1000 600],...
                        'WindowButtonDownFcn',@obj.local_WindowButtonDownFcn);
                    movegui(obj.losses_figure,'center');
                    
                    uicontrol('parent',obj.losses_figure,...
                        'units','normalized','Position',[0.079 0.84 0.13 0.065],...
                        'style','pushbutton',...
                        'Fontsize',12,...
                        'string','Add losses:',...
                        'callback',@obj.Add_losses_callback);
                    
                    obj.lptn_AddLosses_table = uitable('parent',obj.losses_figure,...
                        'units','normalized','Position',[0.08 0.20 0.48 0.635],...
                        'ColumnFormat', {'char','char'},...
                        'ColumnEditable',[false true],...
                        'cellSelectionCallback',@obj.LossesSelectionCallback,...
                        'CellEditCallback',@obj.LossesEditCallback,...
                        'ColumnName', {'Components','Settings'},'RowName','',...
                        'ButtonDownFcn',@obj.local_ButtonDownFcn,...
                        'ColumnWidth',{234},'Data',[obj.lptn_AddLosses_table_data_components',obj.lptn_AddLosses_table_data_settings']);
                    
                    obj.data.ShowGlobalNumSym(obj.losses_figure,[0.63 0.65 0.31 0.2])
                    obj.data.ShowGlobalMotorinput(obj.losses_figure,[0.63 0.38 0.31 0.2])
                    obj.data.ShowMeasurement(obj.losses_figure,[0.63 0.083 0.31 0.25])
                    uicontrol('parent',obj.losses_figure,...
                        'units','normalized','Position',[0.9 0.018 0.07 0.05],...
                        'style','pushbutton',...
                        'Fontsize',9,...
                        'callback',@obj.lptn_save_loss_pb_callback,...
                        'string','Save');
                    uicontrol('parent',obj.losses_figure,...
                        'units','normalized','Position',[0.488 0.21 0.07 0.05],...
                        'style','pushbutton',...
                        'Fontsize',9,...
                        'callback',@obj.lptn_delete_loss_pb_callback,...
                        'string','delete');
                    
                elseif ishandle(obj.losses_figure)
                    figure(obj.losses_figure)
                end
            end
        end
        function lptn_delete_loss_pb_callback(obj, ~,~)
            
            obj.lptn_AddLosses_table_data_components(obj.loss_edit_row) = [];
            obj.lptn_AddLosses_table_data_settings(obj.loss_edit_row)=[];
            tabledata = [obj.lptn_AddLosses_table_data_components',obj.lptn_AddLosses_table_data_settings'];
            %             tabledata(cellfun(@isempty,tabledata))=[];
            set(obj.lptn_AddLosses_table,'data',tabledata);
        end
        function  LossesSelectionCallback(obj,~,callbackdata)
            if length(callbackdata.Indices) >1
                obj.loss_edit_row= callbackdata.Indices(1);
            obj.loss_edit_col= callbackdata.Indices(2);
            end
        end
        function local_ButtonDownFcn(obj, ~,~)
            switch get(obj.lptn_AddLosses_table,'SelectionType')
                case 'normal'
                    disp('µ¥»÷Êó±ê×ó¼ü')
                case 'extend'
                    disp( 'Shift+×ó¼ü£¬»òÕßÍ¬Ê±°´×óÓÒ¼ü')
                case 'alt'
                    disp( 'Ctrl+×ó¼ü£¬»òÕßµ¥»÷ÓÒ¼ü');
                case 'open'
                    disp('Ë«»÷Êó±ê×ó¼ü')
            end
        end
        function local_WindowButtonDownFcn(obj, ~,~)
            switch get(obj.losses_figure,'SelectionType')
                case 'normal'
                    disp('µ¥»÷Êó±ê×ó¼ü')
                case 'extend'
                    disp( 'Shift+×ó¼ü£¬»òÕßÍ¬Ê±°´×óÓÒ¼ü')
                case 'alt'
                    disp( 'Ctrl+×ó¼ü£¬»òÕßµ¥»÷ÓÒ¼ü');
                case 'open'
                    disp('Ë«»÷Êó±ê×ó¼ü')
            end
        end
        function Add_losses_callback(obj, ~,~)
            obj.add_losses_figure = figure('menubar','none','name','Losses settings','resize','on','position',[200 100 850 750]);
            movegui(obj.add_losses_figure,'center');
            checkbox = {};
            for index = 1:length(obj.data.lptn_components)
                obj.lptn_components_chosen{index}= false;
            end
            
            uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.01 0.85 0.2 0.1],...
                'style','text',...
                'Fontsize',9.5,...
                'string','1.Choose components');
            uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.01 0.386 0.2 0.1],...
                'style','text',...
                'Fontsize',9.5,...
                'string','2.Choose total losses');
            
            uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.018 0.28 0.15 0.1],...
                'style','text',...
                'Fontsize',9.5,...
                'string','3.Losses settings');
            
            lptn_choose_components_data = [obj.data.lptn_components,obj.lptn_components_chosen'];
            obj.lptn_loss_choose_components_table = uitable('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.05 0.5 0.5 0.41],...
                'ColumnFormat', {'char','logical'},...
                'ColumnEditable',[false,true],...
                'CellEditCallback',@obj.CheckboxEditCallback,...,...
                'ColumnName', {'Components','Check'},'RowName','',...
                'ColumnWidth',{205},'Data',lptn_choose_components_data);
            
            obj.data.UpdatePopupmenu;
            
            uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.02 0.4 0.1 0.038],...
                'style','text',...
                'Fontsize',9,...
                'string','Entry:');
            
            obj.lptn_ChooseComponents_popup{end+1} = uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.12 0.412 0.381 0.03],...
                'style','pop',...
                'Fontsize',9,...
                'string',obj.data.lptn_allglobalsettings,...
                'callback',@obj.lptn_ChooseComponents_popup_callback);
            obj.lptn_ChooseComponents_edit{end+1} = uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.12 0.411 0.362 0.031],...
                'style','edit',...
                'Fontsize',9.5,...
                'string','',...
                'callback',@obj.lptn_ChooseComponents_edit_callback);
            
            NumSymProperties= {};
            len_cellnum = length(obj.data.lptn_cell_numsym);
            for index = 1: len_cellnum
                NumSymProperties{index} = char(obj.data.lptn_cell_numsym{index}.symbolic);
            end
            
            components_losses_pop_str = [{''},NumSymProperties];
            Componentlosses_pro = properties(LPNUtilities.clComponentLosses);
            Componentlosses_pro = Componentlosses_pro(2:end);
            for index = 1: length(Componentlosses_pro)
                uicontrol('parent',obj.add_losses_figure,...
                    'units','normalized','Position',[0.05 0.34-index*0.042 0.5 0.03],...
                    'style','text',...
                    'Fontsize',9,...
                    'HorizontalAlignment','left',...
                    'string',Componentlosses_pro{index});
            end
            
            real_losses_str = {'true','false'};
            uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.35 0.095 0.2 0.03],...
                'style','pop',...
                'Fontsize',9,...
                'value',2,...
                'string',real_losses_str);
            
            obj.flux_name = uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.35 0.135 0.2 0.03],...
                'style','edit',...
                'Fontsize',9,...
                'string','');
            
            obj.refer_temperature = uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.35 0.175 0.2 0.03],...
                'style','pop',...
                'Fontsize',9,...
                'value',1,...
                'string',obj.data.lptn_popupglobalnumsym);
            obj.refer_temperature_edit= uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.35 0.175 0.175 0.03],...
                'style','edit',...
                'Fontsize',9,...
                'value',1,...
                'string',obj.data.lptn_popupglobalnumsym,...
                'callback',@obj.lptn_refer_temperature_edit_callback);
            obj.temperature_dependency_beta = uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.35 0.22 0.2 0.03],...
                'style','pop',...
                'Fontsize',9,...
                'value',1,...
                'string',obj.data.lptn_popupglobalnumsym);
            obj.temperature_dependency_beta_edit = uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.35 0.22 0.175 0.03],...
                'style','edit',...
                'Fontsize',9,...
                'value',1,...
                'string',obj.data.lptn_popupglobalnumsym,...
                'callback',@obj.lptn_temperature_dependency_beta_edit_callback);
            obj.temperature_dependency = uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.35 0.27 0.2 0.03],...
                'style','pop',...
                'Fontsize',9,...
                'value',1,...
                'string',obj.data.lptn_popupglobalnumsym);
            obj.temperature_dependency_edit = uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.35 0.27 0.175 0.03],...
                'style','edit',...
                'Fontsize',9.5,...
                'value',1,...
                'string',obj.data.lptn_popupglobalnumsym,...
                'callback',@obj.lptn_temperature_dependency_edit_callback);
            
            obj.flux_gain =  uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.35 0.31 0.2 0.03],...
                'style','pop',...
                'Fontsize',9,...
                'value',1,...
                'string',obj.data.lptn_popupglobalnumsym);
            obj.flux_gain_edit = uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.35 0.31 0.175 0.03],...
                'style','edit',...
                'Fontsize',9.5,...
                'string','',...
                'callback',@obj.lptn_ChooseComponents_edit_callback);
            
            uicontrol('parent',obj.add_losses_figure,...
                'units','normalized','Position',[0.83 0.02 0.115 0.04],...
                'style','pushbutton',...
                'Fontsize',9,...
                'string','Enter',...
                'callback',@obj.ChooseComponents_next_callback);
            
            obj.data.ShowGlobalNumSym(obj.add_losses_figure,[0.6 0.7 0.35 0.22])
            obj.data.ShowGlobalMotorinput(obj.add_losses_figure,[0.6 0.4 0.35 0.22])
            obj.data.ShowMeasurement(obj.add_losses_figure,[0.6 0.12 0.35 0.22])
        end
        
        function LossesEditCallback(obj,~,callbackdata)
            index_r = callbackdata.Indices(1);
        end
        
        function lptn_ChooseComponents_edit_callback(obj, eventdata,~)
            str = eventdata.String;
            popupstr = get (obj.lptn_ChooseComponents_popup{end},'String');
            % Check if edit string is found in pop-up list.
            if ismember(str,popupstr)
                set(obj.lptn_ChooseComponents_popup,'value', strmatch(str,popupstr))  % Set the pop-up to match the edit.
            else
                if isnan(str2double(str))
                    warndlg('This variable is not defined.');
                    for index=1:length(obj.lptn_ChooseComponents_popup{end})
                        set(obj.lptn_ChooseComponents_popup{index},'value',1) % Set the edit to current pop-up.
                        set(obj.lptn_ChooseComponents_edit{index},'string','');
                    end
                else
                    obj.lptn_AddLosses_data_settings = str2double(str);
                end
            end
        end
        
        function lptn_ChooseComponents_popup_callback(obj, eventdata,~)
            str = eventdata.String;
            val = eventdata.Value;
            obj.lptn_AddLosses_data_settings= str{val};
            for index=1:length(obj.lptn_ChooseComponents_edit)
                set(obj.lptn_ChooseComponents_edit{index},'String',str{val});
            end
        end
        
        function CheckboxEditCallback(obj,~,callbackdata)
            index_r = callbackdata.Indices(1);
            obj.lptn_components_chosen{index_r} = callbackdata.EditData;
        end
        
        function lptn_save_loss_pb_callback(obj, ~,~)
            close(obj.losses_figure);
        end
        
        function ChooseComponents_next_callback(obj, ~,~)
            lptn_AddLosses_components = ''; count=0;
            for index = 1:length(obj.data.lptn_components)
                if obj.lptn_components_chosen{index} == 1
                    if count == 0
                        lptn_AddLosses_components = obj.data.lptn_components{index};
                    else
                        lptn_AddLosses_components = [lptn_AddLosses_components,',',obj.data.lptn_components{index}];
                    end
                    count = count+1;
                end
            end
            if count > 1
                if isempty(get(obj.flux_name,'string'))
                    warndlg('Must type in global name.');
                else
                    obj.lptn_AddLosses_table_data_settings{end+1} = obj.lptn_AddLosses_data_settings;
                    obj.lptn_AddLosses_table_data_components{end+1} =  lptn_AddLosses_components;
                    close(obj.add_losses_figure);
                    set(obj.lptn_AddLosses_table,'data',[obj.lptn_AddLosses_table_data_components',obj.lptn_AddLosses_table_data_settings']);
                    obj.data.lptn_losses = [obj.lptn_AddLosses_table_data_components',obj.lptn_AddLosses_table_data_settings'];
                end
            else
                obj.lptn_AddLosses_table_data_settings{end+1} = obj.lptn_AddLosses_data_settings;
                obj.lptn_AddLosses_table_data_components{end+1} =  lptn_AddLosses_components;
                close(obj.add_losses_figure);
                set(obj.lptn_AddLosses_table,'data',[obj.lptn_AddLosses_table_data_components',obj.lptn_AddLosses_table_data_settings']);
                obj.data.lptn_losses = [obj.lptn_AddLosses_table_data_components',obj.lptn_AddLosses_table_data_settings'];
            end
        end
        
        
        function lptn_add_sensor_pb_callback(obj, ~,~)
            if obj.data.lptn_apply_state== 0
                warndlg('The machine has not been constructed yet.');
            else
                     if isempty(obj.add_sensors_figure)|| ~ishandle(obj.add_sensors_figure)
                    obj.add_sensors_figure = figure('menubar','none','name','Sensors settings','resize','on','position',[200 100 1000 800]);
                    movegui(obj.add_sensors_figure,'center');
                    
                    for index = 1:length(obj.data.lptn_components)
                        obj.lptn_sensors_components_checkbox_chosen{index}= false;
                    end
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.85 0.2 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','1.Choose components');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.005 0.43 0.15 0.05],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','2.Set position');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.25 0.2 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','3.Choose measurements:');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.02 0.18 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','4.Set xxx:');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.14 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Clamped');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.10 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Inserted');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.06 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Clamped');
                    
                    lptn_choose_components_data = [obj.data.lptn_components,obj.lptn_sensors_components_checkbox_chosen'];
                    obj.lptn_sensors_choose_components_table = uitable('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.5 0.5 0.4],...
                        'ColumnFormat', {'char','logical'},...
                        'ColumnEditable',[false,true],...
                        'CellEditCallback',@obj.SensorsCheckboxEditCallback,...,...
                        'ColumnName', {'Components','Check'},'RowName','',...
                        'ColumnWidth',{205},'Data',lptn_choose_components_data);
                    
                    NumSymProperties= {};
                    len_cellnum = length(obj.data.lptn_cell_numsym);
                    for index = 1: len_cellnum
                        NumSymProperties{index} = char(obj.data.lptn_cell_numsym{index}.symbolic);
                    end
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.42 0.1 0.03],...
                        'style','text',...
                        'Fontsize',9,...
                        'string','Axial');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.15 0.434 0.4 0.027],...
                        'style','pop',...
                        'Fontsize',9,...
                        'string',NumSymProperties,...
                        'callback',@obj.Axial_popup_callback);
                    obj.lptn_sensors_choose_components_axial_position = uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.15 0.43 0.24 0.031],...
                        'Fontsize',9,'string','');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.385 0.09 0.03],...
                        'style','text',...
                        'Fontsize',9,...
                        'string','Radial');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.15 0.39 0.255 0.031],...
                        'style','pop',...
                        'Fontsize',9.5,...
                        'string',NumSymProperties,...
                        'callback',@obj.Radial_popup_callback);
                    obj.lptn_sensors_choose_components_radial_position = uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.15 0.388 0.24 0.032],...
                        'Fontsize',9,'string','');
                    
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.03 0.35 0.13 0.03],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Tangential');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.15 0.349 0.255 0.031],...
                        'style','pop',...
                        'Fontsize',9.5,...
                        'string',NumSymProperties,...
                        'callback',@obj.Tangential_popup_callback);
                    obj.lptn_sensors_choose_components_tangential_position = uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.15 0.348 0.24 0.030],...
                        'Fontsize',9,'string','');
                    
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.45 0.34 0.1 0.05],...
                        'style','text',...
                        'Fontsize',10,...
                        'string','Relative');
                    
                    
                    uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.43 0.35 0.0446 0.05],...
                        'Fontsize',9,...
                        'callback',@obj.Callback_lptn_sensors_setting_position_relative);
                    
                    obj.lptn_sensors_thermalsetting1 = uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.09 0.21 0.065 0.04],...
                        'Fontsize',9,...
                        'callback',@obj.lptn_sensors_thermalsetting1_callback);
                    obj.lptn_sensors_thermalsetting2 = uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.09 0.17 0.065 0.04],...
                        'Fontsize',9,...
                        'callback',@obj.lptn_sensors_thermalsetting2_callback);
                    obj.lptn_sensors_thermalsetting3 = uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.09 0.13 0.065 0.04],...
                        'Fontsize',9,...
                        'callback',@obj.lptn_sensors_thermalsetting3_callback);
                    
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.12 0.21 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.3 0.21 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.12 0.17 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.3 0.17 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.12 0.13 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.3 0.13 0.15 0.031],...
                        'Fontsize',9,'string','');
                    
                    MeasurementXaxis= {''};
                    len_cellmeasure = length(obj.data.lptn_cell_measurement);
                    for index = 1: len_cellmeasure
                        MeasurementAdded = obj.data.lptn_cell_measurement{index};
                        MeasurementXaxis{end+1} = MeasurementAdded{1,2};
                    end
                    
                    obj.lptn_sensor_measurement_popup{end+1} = uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.26 0.445 0.06],...
                        'style','pop',...
                        'Fontsize',9,...
                        'string',MeasurementXaxis);
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.8 0.04 0.115 0.04],...
                        'style','pushbutton',...
                        'Fontsize',9,...
                        'string','Next',...
                        'callback',@obj.AddSensors_next_callback);
                    
                    obj.data.ShowGlobalNumSym(obj.add_sensors_figure,[0.63 0.7 0.31 0.2])
                    obj.data.ShowGlobalMotorinput(obj.add_sensors_figure,[0.63 0.43 0.31 0.2])
                    obj.data.ShowMeasurement(obj.add_sensors_figure,[0.63 0.133 0.31 0.25])
                    
                elseif ishandle(obj.add_sensors_figure)
                    figure(obj.add_sensors_figure)
                end
            end
        end

              
        
        function lptn_save_sensor_pb_callback(obj, ~,~)
            close(obj.sensor_figure);
        end
        
        function AddSensors_callback(obj, ~,~)
            if obj.data.lptn_apply_state== 0
                warndlg('The machine has not been constructed yet.');
            else
                if isempty(obj.add_sensors_figure)|| ~ishandle(obj.add_sensors_figure)
                    obj.add_sensors_figure = figure('menubar','none','name','Sensors settings','resize','on','position',[200 100 1000 800]);
                    movegui(obj.add_sensors_figure,'center');
                    
                    for index = 1:length(obj.data.lptn_components)
                        obj.lptn_sensors_components_checkbox_chosen{index}= false;
                    end
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.85 0.2 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','1.Choose components');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.005 0.43 0.15 0.05],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','2.Set position');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.25 0.2 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','3.Choose measurements:');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.02 0.18 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','4.Set xxx:');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.14 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Clamped');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.10 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Inserted');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.01 0.06 0.1 0.1],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Clamped');
                    
                    lptn_choose_components_data = [obj.data.lptn_components,obj.lptn_sensors_components_checkbox_chosen'];
                    obj.lptn_sensors_choose_components_table = uitable('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.5 0.5 0.4],...
                        'ColumnFormat', {'char','logical'},...
                        'ColumnEditable',[false,true],...
                        'CellEditCallback',@obj.SensorsCheckboxEditCallback,...,...
                        'ColumnName', {'Components','Check'},'RowName','',...
                        'ColumnWidth',{205},'Data',lptn_choose_components_data);
                    
                    NumSymProperties= {};
                    len_cellnum = length(obj.data.lptn_cell_numsym);
                    for index = 1: len_cellnum
                        NumSymProperties{index} = char(obj.data.lptn_cell_numsym{index}.symbolic);
                    end
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.42 0.1 0.03],...
                        'style','text',...
                        'Fontsize',9,...
                        'string','Axial');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.15 0.434 0.4 0.027],...
                        'style','pop',...
                        'Fontsize',9,...
                        'string',NumSymProperties,...
                        'callback',@obj.Axial_popup_callback);
                    obj.lptn_sensors_choose_components_axial_position = uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.15 0.43 0.24 0.031],...
                        'Fontsize',9,'string','');
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.385 0.09 0.03],...
                        'style','text',...
                        'Fontsize',9,...
                        'string','Radial');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.15 0.39 0.255 0.031],...
                        'style','pop',...
                        'Fontsize',9.5,...
                        'string',NumSymProperties,...
                        'callback',@obj.Radial_popup_callback);
                    obj.lptn_sensors_choose_components_radial_position = uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.15 0.388 0.24 0.032],...
                        'Fontsize',9,'string','');
                    
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.03 0.35 0.13 0.03],...
                        'style','text',...
                        'Fontsize',9.5,...
                        'string','Tangential');
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.15 0.349 0.255 0.031],...
                        'style','pop',...
                        'Fontsize',9.5,...
                        'string',NumSymProperties,...
                        'callback',@obj.Tangential_popup_callback);
                    obj.lptn_sensors_choose_components_tangential_position = uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.15 0.348 0.24 0.030],...
                        'Fontsize',9,'string','');
                    
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.45 0.34 0.1 0.05],...
                        'style','text',...
                        'Fontsize',10,...
                        'string','Relative');
                    
                    
                    uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.43 0.35 0.0446 0.05],...
                        'Fontsize',9,...
                        'callback',@obj.Callback_lptn_sensors_setting_position_relative);
                    
                    obj.lptn_sensors_thermalsetting1 = uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.09 0.21 0.065 0.04],...
                        'Fontsize',9,...
                        'callback',@obj.lptn_sensors_thermalsetting1_callback);
                    obj.lptn_sensors_thermalsetting2 = uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.09 0.17 0.065 0.04],...
                        'Fontsize',9,...
                        'callback',@obj.lptn_sensors_thermalsetting2_callback);
                    obj.lptn_sensors_thermalsetting3 = uicontrol('parent',obj.add_sensors_figure,'style','checkbox',...
                        'units','normalized','Position',[0.09 0.13 0.065 0.04],...
                        'Fontsize',9,...
                        'callback',@obj.lptn_sensors_thermalsetting3_callback);
                    
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.12 0.21 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.3 0.21 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.12 0.17 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.3 0.17 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.12 0.13 0.15 0.031],...
                        'Fontsize',9,'string','');
                    uicontrol('parent',obj.add_sensors_figure,'style','edit',...
                        'units','normalized','Position',[0.3 0.13 0.15 0.031],...
                        'Fontsize',9,'string','');
                    
                    MeasurementXaxis= {''};
                    len_cellmeasure = length(obj.data.lptn_cell_measurement);
                    for index = 1: len_cellmeasure
                        MeasurementAdded = obj.data.lptn_cell_measurement{index};
                        MeasurementXaxis{end+1} = MeasurementAdded{1,2};
                    end
                    
                    obj.lptn_sensor_measurement_popup{end+1} = uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.05 0.26 0.445 0.06],...
                        'style','pop',...
                        'Fontsize',9,...
                        'string',MeasurementXaxis);
                    
                    uicontrol('parent',obj.add_sensors_figure,...
                        'units','normalized','Position',[0.8 0.04 0.115 0.04],...
                        'style','pushbutton',...
                        'Fontsize',9,...
                        'string','Next',...
                        'callback',@obj.AddSensors_next_callback);
                    
                    obj.data.ShowGlobalNumSym(obj.add_sensors_figure,[0.63 0.7 0.31 0.2])
                    obj.data.ShowGlobalMotorinput(obj.add_sensors_figure,[0.63 0.43 0.31 0.2])
                    obj.data.ShowMeasurement(obj.add_sensors_figure,[0.63 0.133 0.31 0.25])
                    
                elseif ishandle(obj.add_sensors_figure)
                    figure(obj.add_sensors_figure)
                end
            end
        end
        
        
        function Callback_lptn_sensors_setting_position_relative(obj, eventdata,~)
            if eventdata.Value==1
                type_axial_position = str2num(get(obj.lptn_sensors_choose_components_axial_position,'String'));
                type_radial_position = str2num(get(obj.lptn_sensors_choose_components_radial_position,'String'));
                type_tangential_position = str2num(get(obj.lptn_sensors_choose_components_tangential_position,'String'));
                set(obj.lptn_sensors_choose_components_axial_position,'String',num2str(type_axial_position./obj.component_size_axial));
                set(obj.lptn_sensors_choose_components_radial_position,'String',num2str(type_radial_position./obj.component_size_radial));
                set(obj.lptn_sensors_choose_components_tangential_position,'String',num2str((type_tangential_position./obj.component_size_tangential)));
            else
                type_axial_position = str2num(get(obj.lptn_sensors_choose_components_axial_position,'String'));
                type_radial_position = str2num(get(obj.lptn_sensors_choose_components_radial_position,'String'));
                type_tangential_position = str2num(get(obj.lptn_sensors_choose_components_tangential_position,'String'));
                set(obj.lptn_sensors_choose_components_axial_position,'String',num2str(type_axial_position*obj.component_size_axial));
                set(obj.lptn_sensors_choose_components_radial_position,'String',num2str(type_radial_position*obj.component_size_radial));
                set(obj.lptn_sensors_choose_components_tangential_position,'String',num2str((type_tangential_position*obj.component_size_tangential)));
            end
            
        end
        function Radial_popup_callback(obj, eventdata,~)
            str = eventdata.String;
            val = eventdata.Value;
            set(obj.lptn_sensors_choose_components_radial_position,'string',str{val});
        end
        
        function Axial_popup_callback(obj, eventdata,~)
            str = eventdata.String;
            val = eventdata.Value;
            set(obj.lptn_sensors_choose_components_axial_position,'string',str{val});
        end
        
        function Tangential_popup_callback(obj, eventdata,~)
            str = eventdata.String;
            val = eventdata.Value;
            set(obj.lptn_sensors_choose_components_tangential_position,'string',str{val});
        end
        
        function lptn_sensors_thermalsetting1_callback(obj, eventdata,~)
            set(obj.lptn_sensors_thermalsetting2,'value',0);
            set(obj.lptn_sensors_thermalsetting3,'value',0);
        end
        
        function lptn_sensors_thermalsetting2_callback(obj, eventdata,~)
            set(obj.lptn_sensors_thermalsetting1,'value',0);
            set(obj.lptn_sensors_thermalsetting3,'value',0);
        end
        
        function lptn_sensors_thermalsetting3_callback(obj, eventdata,~)
            set(obj.lptn_sensors_thermalsetting2,'value',0);
            set(obj.lptn_sensors_thermalsetting1,'value',0);
        end
        
        function SensorsCheckboxEditCallback(obj,~,callbackdata)
            index_r = callbackdata.Indices(1);
            for index = 1:length(obj.lptn_sensors_components_checkbox_chosen)
                obj.lptn_sensors_components_checkbox_chosen{index} = 0;
            end
            obj.lptn_sensors_components_checkbox_chosen{index_r} = callbackdata.EditData;
            lptn_choose_components_data = [obj.data.lptn_components,obj.lptn_sensors_components_checkbox_chosen'];
            set(obj.lptn_sensors_choose_components_table,'Data',lptn_choose_components_data);
            %% new
            checked_component = obj.data.obj_lptn.GetCellObjComponent(lptn_choose_components_data{index_r,1});
            checked_component = checked_component{1};
            %radial
            obj.component_size_radial = double(checked_component.GetLength(1));
            obj.component_size_radial_in = double(checked_component.GetRadiusIn);
            obj.component_size_radial_out = double(checked_component.GetRadiusOut);
            %tangential
            obj.component_size_tangential = double(checked_component.GetLength(2));
            %axial
            obj.component_size_axial = double(checked_component.GetLength(3));
            
            set(obj.lptn_sensors_choose_components_axial_position,'String',num2str(obj.component_size_axial));
            set(obj.lptn_sensors_choose_components_radial_position,'String',num2str(obj.component_size_radial));
            set(obj.lptn_sensors_choose_components_tangential_position,'String',num2str(obj.component_size_tangential));
        end
        
        function AddSensors_next_callback(obj, ~,~)
            for index = 1:length(obj.data.lptn_components)
                if obj.lptn_sensors_components_checkbox_chosen{index} == 1
                    obj.lptn_AddSensors_table_data_components{end+1} = obj.data.lptn_components{index};
                    row = index;
                    obj.sensor_position_x{end+1} = get(obj.lptn_sensors_choose_components_axial_position,'String');
                    obj.sensor_position_y{end+1} = get(obj.lptn_sensors_choose_components_radial_position,'String');
                    obj.sensor_position_z{end+1} = get(obj.lptn_sensors_choose_components_tangential_position,'String');
                    AddSensors_position = [obj.sensor_position_x{end},',',obj.sensor_position_y{end},',',obj.sensor_position_z{end}];
                    obj.lptn_AddSensors_table_data_position{end+1} = AddSensors_position;
                    
                    str = get(obj.lptn_sensor_measurement_popup{end},'String');
                    val= get(obj.lptn_sensor_measurement_popup{end}, 'Value');
                    obj.lptn_AddSensors_table_data_measurement{end+1} = str{val};
                end
            end
            close(obj.add_sensors_figure);
            
            obj.data.lptn_sensors = [obj.lptn_AddSensors_table_data_components',obj.lptn_AddSensors_table_data_position',obj.lptn_AddSensors_table_data_measurement'];
%             set(obj.lptn_AddSensors_table,'data',obj.data.lptn_sensors);
            
            obj.lptn_all_components_information_table_data(row,7) = {[AddSensors_position,str{val}]};
            set(obj.lptn_all_components_information_table,'data',obj.lptn_all_components_information_table_data);
        end
        
         function AddSensors_next_edit_callback(obj, ~,~)
           x= strcmp(obj.data.lptn_sensors,obj.data.lptn_components{obj.edit_row});       
                    obj.sensor_position_x{x} = get(obj.lptn_sensors_choose_components_axial_position,'String');
                    obj.sensor_position_y{x} = get(obj.lptn_sensors_choose_components_radial_position,'String');
                    obj.sensor_position_z{x} = get(obj.lptn_sensors_choose_components_tangential_position,'String');
                    AddSensors_position = [obj.sensor_position_x{x},',',obj.sensor_position_y{x},',',obj.sensor_position_z{x}];
                    obj.data.lptn_sensors{x,2} = AddSensors_position;
                    str = get(obj.lptn_sensor_measurement_popup{end},'String');
                    val= get(obj.lptn_sensor_measurement_popup{end}, 'Value');
                    obj.data.lptn_sensors{x,3} = str{val};
              
            close(obj.add_sensors_figure);
            obj.lptn_all_components_information_table_data(obj.edit_row,7) = {[AddSensors_position,str{val}]};
            set(obj.lptn_all_components_information_table,'data',obj.lptn_all_components_information_table_data);
         end
        
        function lptn_Component_temperature_callback(obj, ~,~)
            if obj.data.lptn_apply_state== 0
                warndlg('The machine has not been constructed yet.');
            else
                obj.Component_temperature_figure = figure('menubar','none','name','Component temperature input settings','resize','on','position',[200 100 750 500]);
                movegui(obj.Component_temperature_figure,'center');
                len = length(obj.data.lptn_components);
                if isempty(obj.lptn_Component_temperature_dimension)
                    for index = 1:len
                        obj.lptn_Component_temperature_input{index} = '';
                        obj.lptn_Component_temperature_dimension{index} = 'uniform';
                    end
                end
                
                Component_temperature_table_data=[obj.data.lptn_components,obj.lptn_Component_temperature_input',obj.lptn_Component_temperature_dimension'];
                dimension = {'uniform','radial positive','radial negative','axial positive','axial negative',...
                    'tangential positive','tangential negative'};
                obj.lptn_Component_temperature_table = uitable('parent',obj.Component_temperature_figure,...
                    'units','normalized','Position',[0.15 0.2 0.6 0.65],...
                    'ColumnFormat', {'char','char',dimension},...
                    'ColumnEditable',[false,true,true,true],...
                    'CellEditCallback',@obj.Component_temperature_EditCallback,...,...
                    'ColumnName', {'Components','Entry temperature','Dimensions'},'RowName','',...
                    'ColumnWidth',{140},'Data',Component_temperature_table_data);
                
                uicontrol('parent',obj.Component_temperature_figure,'style','pushbutton',...
                    'units','normalized','Position',[0.8 0.1 0.06 0.046],...
                    'Fontsize',9,'callback',@obj.apply_Component_temperature_pb_callback,'string','OK');
                
                set(obj.lptn_Component_temperature_table,'Tag','myTableTag')
            end
        end
        
        
        function Component_temperature_EditCallback(obj,~,callbackdata)
            myfigure=findobj('Tag','myTableTag');
            index_r = callbackdata.Indices(1);
            index_c = callbackdata.Indices(2);
            if index_c  == 2
                str = callbackdata.EditData;
                if isempty(str2num(str))
                    obj.lptn_Component_temperature_input{index_r} = 0;
                    warndlg('Input must be numerical');
                else
                    obj.lptn_Component_temperature_input{index_r} = callbackdata.EditData;
                end
            else
                obj.lptn_Component_temperature_dimension{index_r} = callbackdata.EditData;
            end
            
            Component_temperature_table_data=[obj.data.lptn_components,obj.lptn_Component_temperature_input',obj.lptn_Component_temperature_dimension'];
            set(findobj(myfigure,'Tag','myTableTag'),'Data',Component_temperature_table_data)
            obj.data.lptn_components_input_temperature = Component_temperature_table_data;
        end
        
        
        function apply_Component_temperature_pb_callback(obj, ~,~)
            close(obj.Component_temperature_figure);
            
            obj.lptn_all_components_information_table_data(:,8) = obj.data.lptn_components_input_temperature(:,2);
            obj.lptn_all_components_information_table_data(:,9) = obj.data.lptn_components_input_temperature(:,3);
            
            set(obj.lptn_all_components_information_table,'data',obj.lptn_all_components_information_table_data);
            
        end
        
        
        
        function lptn_Component_output_callback(obj, ~,~)
            if obj.data.lptn_apply_state== 0
                warndlg('The machine has not been constructed yet.');
            else
                obj.Component_output_figure = figure('menubar','none','name','Component temperature output','resize','on','position',[200 100 800 600]);
                movegui(obj.Component_output_figure,'center');
                len = length(obj.data.lptn_components);
                if isempty(obj.lptn_Component_temperature_choose)
                    obj.lptn_Component_temperature_choose = cell(len,2);
                    for index = 1:len
                        obj.lptn_Component_temperature_choose(index,:) = {'false','false'};
                    end
                end
                if isempty(obj.data.lptn_initial_temperature)
                    for index = 1:len
                        obj.data.lptn_initial_temperature{index} = '';
                    end
                end
                
                Component_output_table_data=[obj.data.lptn_components,obj.data.lptn_initial_temperature',obj.lptn_Component_temperature_choose(:,1),...
                    obj.lptn_Component_temperature_choose(:,2)];
                obj.lptn_Component_output_table= uitable('parent',obj.Component_output_figure,...
                    'units','normalized','Position',[0.1 0.3 0.78 0.55],...
                    'ColumnFormat', {'char','char','logical','logical'},...
                    'ColumnEditable',[false,true,true,true],...
                    'CellEditCallback',@obj.Component_temperature_output_EditCallback,...,...
                    'ColumnName', {'Components','Initial temperature','Average temperature','Hotspot temperature'},'RowName','',...
                    'ColumnWidth',{152},'Data',Component_output_table_data);
                
                uicontrol('parent',obj.Component_output_figure,'style','pushbutton',...
                    'units','normalized','Position',[0.8 0.1 0.06 0.046],...
                    'Fontsize',9,'callback',@obj.apply_Component_output_table_pb_callback,'string','OK');
                
                set(obj.lptn_Component_output_table,'Tag','myTableTag2')
            end
        end
        
        
        function Component_temperature_output_EditCallback(obj,~,callbackdata)
            myfigure=findobj('Tag','myTableTag2');
            index_r = callbackdata.Indices(1);
            index_c = callbackdata.Indices(2);
            if index_c  == 2
                obj.data.lptn_initial_temperature{index_r} = callbackdata.EditData;
            elseif index_c  == 3
                if callbackdata.EditData == 1
                    obj.lptn_Component_temperature_choose{index_r,1} = 'true';
                else
                    obj.lptn_Component_temperature_choose{index_r,1} =  'false';
                end
            else
                if callbackdata.EditData == 1
                    obj.lptn_Component_temperature_choose{index_r,2} =  'true';
                else
                    obj.lptn_Component_temperature_choose{index_r,2} =  'false';
                end
                
            end
            Component_output_table_data=[obj.data.lptn_components,obj.data.lptn_initial_temperature',obj.lptn_Component_temperature_choose(:,1),...
                obj.lptn_Component_temperature_choose(:,2)];
            set(findobj(myfigure,'Tag','myTableTag2'),'Data',Component_output_table_data)
            obj.data.lptn_components_output_temperature = Component_output_table_data;
        end
        
        
        
        function apply_Component_output_table_pb_callback(obj, ~,~)
            obj.lptn_all_components_information_table_data(:,10) = obj.data.lptn_initial_temperature';
            obj.lptn_all_components_information_table_data(:,11) = obj.lptn_Component_temperature_choose(:,1);
            obj.lptn_all_components_information_table_data(:,12) = obj.lptn_Component_temperature_choose(:,2);
            set(obj.lptn_all_components_information_table,'data',obj.lptn_all_components_information_table_data);
            close(obj.Component_output_figure);
        end
        
        
    end
    
end

